<?php

/**
 * @file
 * Provides a type_pizza entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function type_pizza_theme() {
  return [
    'type_pizza' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for type_pizza templates.
 *
 * Default template: type-pizza.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the type_pizza information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_type_pizza(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
