<?php

/**
 * @file
 * Provides a doss_ent entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function doss_ent_theme() {
  return [
    'doss_ent' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for doss_ent templates.
 *
 * Default template: doss-ent.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the doss_ent information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_doss_ent(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
